# References https://gist.github.com/dan-blanchard/7045057
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

branches:
  only:
    #- master
    - devel
    #- release
    #- devpatches

before_install:
  # Install Miniconda
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-2.2.2-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # The next couple lines fix a crash with multiprocessing on Travis
  # and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
    - conda update --yes conda
    # Install NumPy LLVM
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy llvm
    # Install unittest2 for Python 2
    - if [ ${TRAVIS_PYTHON_VERSION:0:3} == "2.6" ]; then conda install unittest2; fi
    # Install llvmpy
    - git clone git://github.com/llvmpy/llvmpy.git -q
    - cd llvmpy ; python setup.py install -q >/dev/null ; cd ..
    # Install numba
    - python setup.py install -q >/dev/null

script: cd ~; python -c "import sys;import numba;sys.exit(0 if numba.test() else 1)"

notifications:
  email: false
  flowdock: "cb7bc57e58b3d42f77685f93211c03ab"
  on_success: "change"
  on_failure: "always" # "change"

