language: python

python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "pypy"

branches:
  only:
    - master
    - devel

install:
    - pip install -r requirements.txt --use-mirrors
    - python setup.py build_ext --inplace

script: nosetests

matrix:
  allow_failures:
    - python: pypy

