# Environment loosely based on https://github.com/conda/conda/blob/master/appveyor.yml

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\buildscripts\\appveyor\\run_with_env.cmd"

  matrix:
    # Since appveyor is quite slow, we only use a single configuration
    # and a subset of the test suite (see build_and_test.bat)
    - ARCH_SUFFIX: "-x64"
      CONDA_PY: "3.5"
      CONDA_NPY: "1.11"

init:
  # Use AppVeyor's provided Miniconda: https://www.appveyor.com/docs/installed-software#python
  - set MINICONDA=C:\Miniconda35%ARCH_SUFFIX%
  - set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%

install:
  # Uncomment to download and install the latest Miniconda (XXX flaky)
  #- powershell .\\buildscripts\\appveyor\\install.ps1
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info
  - conda list

build: false

test_script:
  # Build and test the package
  - cmd /C .\\buildscripts\\appveyor\\build_and_test.bat
