jobs:
- template: buildscripts/azure/azure-macos.yml
  parameters:
    name: macOS
    vmImage: xcode9-macos10.13
- template: buildscripts/azure/azure-linux.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
- template: buildscripts/azure/azure-windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2017
- template: buildscripts/azure/azure-windows-py27.yml
  parameters:
    name: WindowsPy27
    vmImage: vs2017-win2017
