# Configuration for codecov.io

comment:
    layout: "header, changes, diff"

coverage:
    ignore:
        - "numba/cuda/.*"
        - "numba/hsa/.*"

    status:
        # This check can mark a build failed if too much new code
        # is not covered (which happens often with JITted functions).
        patch: false
        project:
            default:
                # The build fails if total project coverage drops by more than 3%
                target: auto
                threshold: "3%"
