parameters:
  name: ''
  vmImage: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      py38_np117:
        PYTHON: '3.8'
        NUMPY: '1.17'
        CONDA_ENV: 'testenv'
        TEST_START_INDEX: 16
      py37_np115:
        PYTHON: '3.7'
        NUMPY: '1.15'
        CONDA_ENV: 'testenv'
        TEST_START_INDEX: 17

  steps:
    - task: CondaEnvironment@1
      inputs:
        updateConda: no
        packageSpecs: ''

    # Need to install VC 9.0 only for Python 2.7
    - powershell: |
        $wc = New-Object net.webclient
        $wc.Downloadfile("https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi", "VCForPython27.msi")
        Start-Process "VCForPython27.msi" /qn -Wait
      displayName: 'Install VC 9.0'
      condition: eq(variables['PYTHON'], '2.7')

    - script: |
        buildscripts\\incremental\\setup_conda_environment.cmd
      displayName: 'Before Install'

    # VC 9.0 cannot build tbbpool.cpp in Numba, so we need to remove
    # tbb from the environment before the build stage.
    - script: |
        call activate %CONDA_ENV%
        conda remove -y tbb tbb-devel
      displayName: 'Remove TBB'

    - script: |
        # temporarily patch this in to get a recent TBB
        call activate %CONDA_ENV%
        conda install -c conda-forge -y tbb tbb-devel
      displayName: 'Add in conda-forge TBB'

    - script: |
        buildscripts\\incremental\\build.cmd
      displayName: 'Build'

    - script: |
        call activate %CONDA_ENV%
        python -m numba -s
      displayName: 'Display numba system information'

    - script: |
        call activate %CONDA_ENV%
        python -m numba.tests.test_runtests
      displayName: 'Verify runtests'

    - script: |
        call activate %CONDA_ENV%
        python -m numba.runtests -b -v -g -m 2 -- numba.tests
      displayName: 'Test modified test files'

    - script: |
        call activate %CONDA_ENV%
        python runtests.py -m 2 -b -j "%TEST_START_INDEX%,None,%TEST_COUNT%"  --exclude-tags='long_running'  -- numba.tests
      displayName: 'Test slice of test files'
