package:
  name: numba
  version: {{ environ.get('GIT_DESCRIBE_TAG','') }}

source:
  git_url: git@github.com:numba/numba.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - python
    - argparse        [py26]
    - numpy
    # On channel https://binstar.org/numba/
    - llvmlite 0.6*
    - funcsigs       [py26 or py27]
  run:
    - python
    - argparse        [py26]
    - numpy
    # On channel https://binstar.org/numba/
    - llvmlite 0.6*
    - funcsigs       [py26 or py27]
test:
  requires:
    - argparse       [py26]
    - unittest2      [py26]
    - cudatoolkit    [win64 or linux64 or osx]
    - jinja2
  files:
    - mandel.py
  commands:
    - pycc -h
    - numba -h
