package:
  name: numba-hsa
  version: "0.17.1"

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #entry_points:
  #  - pycc = numba.pycc:main

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - argparse        [py26]
    - numpy
    # On channel https://binstar.org/numba/
    - llvmlite
    - funcsigs       [py26 or py27]
test:
  requires:
    - argparse       [py26]
    - unittest2      [py26]
    - cudatoolkit
  files:
    - mandel.py
  commands:
    - pycc -h
