{% set version = "2018.0.2" %} # this is the intel version to get
{% set build_number = "0" %}   # and the build number from the intel version

package:
  name: icc_rt
  version: {{ version }}

build:
  number: {{ build_number }}

source:
    - url: https://anaconda.org/intel/icc_rt/{{ version }}/download/win-64/icc_rt-{{version}}-intel_{{build_number}}.tar.bz2 # [win]
    - url: https://anaconda.org/intel/icc_rt/{{ version }}/download/osx-64/icc_rt-{{version}}-intel_{{build_number}}.tar.bz2 # [osx]
    - url: https://anaconda.org/intel/icc_rt/{{ version }}/download/linux-64/icc_rt-{{version}}-intel_{{build_number}}.tar.bz2 # [linux]
    - path: scripts

requirements:
  build:
    - python>=3.6

about:
  license: "Intel"
  license_family: "Proprietary"
  license_file: LICENSE.txt
summary: Intel ICC runtime.
