name: 'Mark stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: >
            This issue is marked as stale as it has had no activity in the past
            30 days. Please close this issue if no further response or action is
            needed. Otherwise, please respond with any updates and confirm that
            this issue still needs to be addressed.
          stale-issue-label: 'stale'
          exempt-issue-labels: 'bug,bug - failure to compile,bug - ice,bug - incorrect behaviour,bug - memory leak,bug - miscompile,bug - regression,bug - segfault,performance - compile time,performance - run time,performance,feature_request,enhancement,task,good first issue,good second issue,Blocked awaiting long term feature,Numba 1.0'
          days-before-issue-stale: 30
          days-before-issue-close: -1
